
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.CLSCompliant(true)]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "File not in use", Scope = "member", Target = "~P:SecretSanta.Api.Tests.TestableGiftService.ToReturn")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "File not in use", Scope = "member", Target = "~P:SecretSanta.Api.Tests.TestableGiftService.GetGiftsForUser_UserId")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "File not in use", Scope = "member", Target = "~M:SecretSanta.Api.Tests.TestableGiftService.RemoveGift(System.Int32,System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GiftControllerTests.GetGiftForUser_ReturnsUsersFromService~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GiftControllerTests.GetGiftForUser_RequiresPositiveUserId~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.CreateGroup_RequiresGroup~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.CreateGroup_ReturnsCreatedGroup~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.DeleteGroup_RequiresPositiveId(System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.DeleteGroup_ReturnsNotFoundWhenTheGroupFailsToDelete~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.DeleteGroup_ReturnsOkWhenGroupIsDeleted~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.GetAllGroups_ReturnsGroups~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.UpdateGroup_RequiresGroup~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.UpdateGroup_ReturnsUpdatedGroup~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupUserControllerTests.GetUsersFromGroup_Ok~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.PairingControllerTests.BuildPairingForAGroup_BadRequest_DueToTooFew~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.PairingControllerTests.BuildPairingForAGroup_BadRequest_GroupNotFound~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.PairingControllerTests.BuildPairingForAGroup_Ok~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.UserControllerTests.AddUserViaApi_CompletesSuccessfully~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Testing file", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.UserControllerTests.AddUserViaApi_FailsDueToMissingFirstName~System.Threading.Tasks.Task")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "function call needs the TestContext inorder to work.", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GiftControllerTests.ConfigureAutoMapper(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)")]
