
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GiftControllerTests.GetGiftForUser_ReturnsUsersFromService~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GiftControllerTests.GetGiftForUser_RequiresPositiveUserId~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.CreateGroup_RequiresGroup~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.CreateGroup_ReturnsCreatedGroup~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.DeleteGroup_RequiresPositiveId(System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.DeleteGroup_ReturnsNotFoundWhenTheGroupFailsToDelete~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.DeleteGroup_ReturnsOkWhenGroupIsDeleted~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.GetAllGroups_ReturnsGroups~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.UpdateGroup_RequiresGroup~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.GroupControllerTests.UpdateGroup_ReturnsUpdatedGroup~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.UserControllerTests.AddUserViaApi_CompletesSuccessfully~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Api.Tests.Controllers.UserControllerTests.AddUserViaApi_FailsDueToMissingFirstName~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~P:SecretSanta.Api.Tests.TestableGiftService.GetGiftsForUser_UserId")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:SecretSanta.Api.Tests.TestableGiftService.ToReturn")]

